### ISSUE TITLE
Improve footer

### ISSUE THREAD

**Issue by zugzwang03** [codervivek5/Formfil#142]
I want to improve the footer section by replacing service 1, service 2 by relevant services, replacing the social handles by facebook, gmail, twitter, linkedIn related proper symbols, and also add hovering effect on social icons. Also if you want to attack possible social media links with them, you can send that here, I can attach that. Can I contribute to this under JWOC'23?

![image](https://user-images.githubusercontent.com/95460021/222725866-1d58a77a-7658-48b2-8129-21b1eb131325.png)

**Comment by codervivek5** [comment]
make all social media icons verticle

**Comment by zugzwang03** [comment]
![image](https://user-images.githubusercontent.com/95460021/222882554-ef7a65de-7e92-412e-a0a2-c091bc54baa6.png)
is it fine? @codervivek5

**Comment by codervivek5** [comment]
can you add my email (codervivek5@gmail.com) and social icon make like a button means increase width little bit more so that it look more attractive

**Comment by vk20july** [comment]
I want to work on this issue under jwoc @codervivek5
