### ISSUE TITLE
Link signup page with corresponding link (phase-2)

### ISSUE THREAD

**Issue by SasiVardhan247** [codervivek5/Formfil#152]
Login Page is not linked to signup
![image](https://user-images.githubusercontent.com/83742554/222981844-2c73025b-65da-4189-8a23-613d178754e3.png)

**Comment by Awesomeasma** [comment]
I would like to work on this under JWOC

**Comment by Krupalll20** [comment]
heyyyy @codervivek5 can you assign this issue to me if nobody working on this?
