### ISSUE TITLE
Add badges in readme

### ISSUE THREAD

**Issue by khushimarothi** [codervivek5/Formfil#181]
I want to add badges in readme.
Please assign under JWOC

![Screenshot (38)](https://user-images.githubusercontent.com/85816852/225090025-b292e385-e830-4014-b6c0-4b31f71bd247.png)

**Comment by khushimarothi** [comment]
@codervivek5  Please merge the pending Pr so I can create a pr for this

**Comment by codervivek5** [comment]
ok I will merge your PR
