### ISSUE TITLE
Update contact us

### ISSUE THREAD

**Issue by khushimarothi** [codervivek5/Formfil#199]
Issue:
![Screenshot (68)](https://user-images.githubusercontent.com/85816852/225552173-40c87526-3e3d-4b96-be38-12f109032c78.png)
Keep contact us at the top of the form and improve the spacings and validate form using js. Please assign under JWOC

**Comment by Krupalll20** [comment]
hey @codervivek5 can you assign this issue to me?

**Comment by IM-TECHNO** [comment]
Currently Working on this issue
