### ISSUE TITLE
Enhancement of Sign up page

### ISSUE THREAD

**Issue by Daffodilgithub** [codervivek5/Formfil#203]
I want to add placeholder , icons and hover effect on submit button etc. Please assign this issue to me under JWOC.
![Screenshot (94)](https://user-images.githubusercontent.com/98342622/225583850-90603f31-c75b-4aa9-88b0-6c57f6e92f3a.png)

**Comment by rahulrana701** [comment]
@codervivek5 I would like to work on this issue please assign it to me..

**Comment by rahulrana701** [comment]
@codervivek5 can you assign it to me , I want to work on this issue...

**Comment by rahulrana701** [comment]
@codervivek5 are you still maintaining the project........

**Comment by rahulrana701** [comment]
@codervivek5 can you suggest me some other issues....

**Comment by codervivek5** [comment]
@RahulRana701 if you really want to work  with me then kindly go to VigyBag repo in my ID. use readme file for your reference and check out that .....after that if you have any issue then drop msg me on instagram or LinkedIn or whenever you want
