### ISSUE TITLE
Home Page

### ISSUE THREAD

**Issue by ritika728** [codervivek5/Formfil#204]
Hey @codervivek5, I would like to open this issue under JWOC. Maybe someone has mismatched the home page, it is completely messed up. I would like to improve it. Please consider giving the hard tag as there are a lot of changes required. Here is how is it looking :

https://user-images.githubusercontent.com/91181981/225597303-20f4efae-0d50-4fc4-afc6-696c71feb056.mp4

**Comment by Viveksati5143** [comment]
Please assign it to me @codervivek5 under JWOC
